jperon/lyluatex

- lyluatex.sty
this removes an extra space created after the score in a ly environment
> Fix spacing in ly environment

- lyluatex.lua
This allows for the user to create conditional constructs inside their lilypond files so that they compile differently when compiled as a stand-alone document and as one which is included in a LaTeX document using lyluatex
Example: the following paper block sets the default paper size to a5 for stand alone documents while still allowing lyluatex to control the line width when used:
\paper {
#(if (not (defined? 'inside-lyluatex))
(set-paper-size "a5"))
}
> Create a flag indicating that the file is being compile through lyluatex

- lyluatex.lua
- lyluatex.sty
Closes #23 
I think this is ready for review now.
There are further things to consider from a user's point of view. With this PR protrusion is "the" behaviour of the package, but there should be other options, for example when the score does *not* fill the whole line width (e.g. centered, short music examples). But I think this could be discussed *after* merging this.
> Protrusion

- lyluatex.lua
This is a preliminary implementation of #30 that properly detects and handles cases where LilyPond fails to compile a score.
I *think* I correctly identify the case with both fragment and full-page scores (which is completely different), but the consequence is preliminary: at the current state of opening that pull request a failed score inserts a placeholder comment *in the output document*, and we should discuss what else we could do (so this isn't meant to be merged yet).
One suggestion that might be acceptable to both @rpspringuel 's and my perspective would be to rewrite the text that is written to LaTeX to include a file with a file name "compilation-failure.pdf" or similar. That way "plain" LaTeX would simply choke about the missing file while `musicexamples` would print that yellow …
> WIP: #30: Correctly identify and handle failed LilyPond compilations

- Makefile
- lyluatex.lua
- lyluatex.md
- lyluatex.sty
- lyluatexmanual.cls
- test-alignment.tex
Fixes #32
Document fonts can now be injected into the LilyPond score:
* By default the *current* font will become the roman font in LilyPond
* but it can be set so the three families are passed directly
* can be switched on and off globally/locally and along the way
**Note:** So far works only for "fragments" as we don't inject *any* layout into included files, see #29
> Fonts to lilypond

- lyluatex.lua
- lyluatex.sty
Margins are now auto-calculated for fullpage scores.
It could sometimes need a manual `\newpage` to get the good page number.
> Fullpage margins

- ly/Beethoven/opus-18-1.ly
- lyluatex.lua
- lyluatex.sty
- test.tex
This Pull Request implements vertical alignment for fullpage scores with two options:
* `fullpagealign=crop`
* `fullpagealign=staffline`
* `\lilypondFullpageAlign{crop/staffline}`
With `crop` the crop box of the LilyPond score is aligned to the typearea box of the text document:
With `staffline` the outermost lines of the staff symbol will be aligned, with any additional score items protruding into the margins:
I have set `staffline` to be the default because that is consistent how we handle the horizontal protrusion, and because I think that is what we want to have when thinking about beautiful book layout. But we can discuss that.
Probably we should have additional options `extra-top-margin` and `extra-bottom-margin` for manual adjustment for special scores with large protrusion.
> Fullpage vertical align

- lyluatex.lua
- lyluatex.sty
This commit (hopefully) streamlines the program flow in the Lua part by not having arguments flow through the function calls (partially they even changed their names during this flow).
Basically the program flow is now like this:
* `lilypond_file()` and `lilypond_fragment()`
These are the entry functions and produce the content LilyPond code from the LaTeX input
* `process_lilypond_code()`
* First all options are calculated that are needed to determine if the score has to be recompiled.
* If necessary, `apply_lilypond_header()` is called to set up the Lilypond file/code and `run_lilypond()` to actually compile it
* finally the LaTeX code is generated
Everything that can be considered a "property" of the current score is not passed along as arguments anymore but stored as local options. …
> Program flow and passing argument

- lyluatex.lua
- lyluatex.sty
For some reason the "showfailed" option has been forgotten recently.
The behaviour when a to-be-compiled score failed is now:
`showfailed == false`: Produce an error, but print nothing
`showfailed == true`: print the box, but don't produce an error
In addition I changed the default to false
> Take "showfailed" option into account

- lyluatex.lua
- lyluatex.sty
This PR includes two features:
* a `debug-lilypond` option that will save both LilyPond's log and the generated LilyPond code in `<output>.ly` and `<output>.log`
* When LilyPond exits with non-zero status a warning is issued, pointing to the log and the .ly file, which are then kept, regardless of the value of `debug-lilypond`.
**Note:** I assume this doesn't work on Windows, but I didn't find a solution for that. (If that's true then it would probably prevent *any* Lilypond call)
> Debug lilypond and better handling of lilypond failure

- lyluatex.lua
- lyluatex.sty
This allows using single package options (for example `[cleantmp]`), thus
making package options behave as local options.
> Use xkeyval instead of kvoptions

- lyluatex.sty
When the .tex document uses TeX-fonts (i.e. fonts installed in the
texmf tree and not as system fonts passing the text document's fonts to LilyPond will result in the use of ugly fallback fonts. This is usually the case
when the user creates a simple document without explicit font settings.
When weighing between not activating a cool lyluatex feature by default
or risking ugly unexpected results I think we should opt for the less interesting
default.
> Discuss: By default don't pass fonts to LilyPond

- .gitignore
PDF, EPS, PS have been commented out in the .gitignore file because they
"might exclude image files for figures".
However, I suggest ignoring them and adding files explicitly if they are
needed for figures etc.
> Discussion: Ignore pdf/eps/ps files

- lyluatex.lua
<<<PAPER>>> is not only substituted once, avoiding having two
separate "indent" clauses in the generated LilyPond code.
<<<PAPER>>> is used for the paper size in fullpage mode and set to ''
in the other modes
<<<INDENT>>> is substituted by the result of ly_indent(),
which now takes into account the presence of 'indent' and 'insert=fullpage'
> Better handling of <<<PAPER>>> substitution

- lyluatex.sty
I found that protecting the option values this way allows to write
```tex
\lysetoption{line-width}{0.8\linewidth}
```
which will make it possible to use that as a "percentage" replacement (#103). (It is already possible to use `0.8\linewidth` as a package or local option (of course raising an error later when trying to calculate a value).)
Please have a careful look if I didn't misunderstand anything and missed any side-effects this change might have.
> Protect options in \lysetoption

- lyluatex.sty
This comment was a leftover from a previous state.
Additional question: is it necessary to do that in the TeX Part?  it seems cleaner to ask for that value directly from Lua, if that's possible.
> Fix obsolete comment

- lyluatex.lua
- lyluatex.sty
Closes #119
When the 'twoside' option is not set (or reset to 'default') full-page scores will inherit the one/twoside option from the .tex document.
When set to either false or true that value is used regardles of the text document's setting.
One special thing had to be considered is LilyPond's behaviour to respect 'inner-margin' only in two-side, 'left-margin' only in one-side mode. The solution was to specify both as equal.
It *may* be desirable to clean that up a bit and write the full code depending on the twoside option instead of only replacing the 't' or 'f'.
> Add 'twoside' option

- lyluatex.lua
- lyluatex.sty
- test.tex
All functions that write LaTeX code are now in a `latex` array. They need to
receive explicit arguments, so that it's clear where each score property is used.
Also fixes #124
> Refactor - fix #116

- lyluatex.sty
We will very often produce overfull hboxes through intended protrusion.
The way to completely suppress the warnings is to temporarily set `\hfuzz` to
a huge value.
Two questions about the approach:
* is it OK to "hijack" `\ly@setunits` for this or should it be implemented in its own macro?
* Is it OK to *completely* suppress the warning?
I think so because we shorten a score not to be cut off at page border and if the user sets max-protrusion to be even higher they should be knowing what they do.
> Suppress "overfull hbox" warnings

- lyluatex.lua
- lyluatex.sty
This option does not return any \includegraphics macros or similar but the raw PDF name(s) (without extension).
For `insert=inline|bare-inline|fullpage` the plain filename is returned, including the tmpdir and the hash (i.e.: `self.output` of the score). 
For `insert=systems` a comma-separated list is returned, containing the file names as above but also the horizontal offset in the first element:
```
-5pt,tmp-ly/my-hash-1,tmp-ly/my-hash-5
```
(when `print-only` is set to `{1,5}` and the left protrusion is 5pt).
Open questions:
* I do currently *not* enclose the return value in braces because I think it is better to consume the plain filename string
* At this point my LaTeX fu is not sufficient to create appropriate wrapper commands. I don't know how I can create a command or environment …
> Raw pdf name output

- .gitignore
- examples/dynamic-indent.tex
- examples/print-only.tex
- ly/eight-systems.ly
- lyluatex.lua
- lyluatex.sty
calc range already in the compilation loop
- check for indent there (not when writing systems to LaTeX)
- deactivate indent when
- only system no. 1 is printed
(because score only has one system or due to print-only)
- the first system is *not* printed first (through print-only)
- if indent is deactivated and the score has more than one system
then recompile without indent to have a properly filled system
(and not one that is just shifted left)
See new example file
Based on #153
> Better handling of suppressed indentation

- lyluatex.lua
- lyluatex.sty
While reviewing the manual section about fonts I changed some small details about the handling of `current-font-as-main`:
- default value is now 'false'
- if `rmfamily` is set then current-font-as-main is unconditionally set to false
- but only when it *is* set in the document a warning is issued
More explanations in https://github.com/jperon/lyluatex/commit/8b9bc1952eef1b94c5c09ca2a71f77099d9a2edf
> Better handling of current-font-as-main

- lyluatex.lua
There was an infinite loop when a score contained invalid LilyPond code.
> Avoid infinite loop when there are errors in LilyPond code.

- lyluatex.lua
This commit allows \lyscore{} to access *any* property of the score
(I noticed the need when I wanted to add a label to a score with
raw-pdf). In addition the argument can still be set to empty, a number,
'nsystems' or 'hoffset'
> Make all score properties available to \lyscore

- lyluatex.lua
- lyluatex.sty
a)
There may be the need to force a first page number (i.e. the start
with an odd or even page), especially in combination with the raw-pdf
option, when the resulting score is not immediately included in a score.
I came across this in a case where I want to first generate a number of
scores and afterwards include them in a row of documents (=> a set
of all parts for a score). I know that the scores will all start on an odd page
(because I'll take care of that) so I want to force LilyPond to think so,
regardless of what lyluatex thinks the "current page" is.
b)
Incidentally I think there may be reasons where the first page number may
*not* be wanted, even when included in a book.
> Add first-page-number and print-first-page-number options

- lyluatex.lua
Closes #197
When including LilyPond files that contain percent characters (i.e.
any comments) they cause the flatten_content() function to fail
because single percent chars are uncorrectly interpreted as
escape characters.
This commit replaces percents with hash characters - which doesn't
do any harm as this flattened LilyPond code will never be used by
LilyPond, only to generate a hash filename. (OTOH simply removing
them might have unwanted side effects).
> Fix crash with comments in included LilyPond files

- lyluatex.lua
- lyluatex.md
- lyluatex.sty
In some cases the heuristics can't detect the need for recompilation because not all content is included through `\include`. In these cases the `force-compilation` option is better than asking the user to determine and remove the score from the temporary directory (which will often be not possible anyway, and the user would have to purge the directory completely).
I think this is pretty uncontroversial, and I'll take the approach of LilyPond's review process: if there are no objections within five days, I'll merge this myself.
> force-compilation option

- lyluatex.md
As per http://tug.org/pipermail/tex-live/2018-April/041493.html the description of the local installation wasn't fully correct.
Actually it's a trivial change, but I'm still not fully sure I haven't misunderstood some details - therefore a pull request.
> Document local installation of current version

- lyluatex.lua
- lyluatex.sty
LISTFILE was set to the *default* value of the tmpdir option because
writing \ExecuteOptionsX to the tex document doesn't update the option.
This has to take place in a new \directlua call.
Fixes #224
> #224: Let LISTFILE respect tmpdir option

- lyluatex.lua
Fixes #227
* Only insert left-margin *or* inner-margin into the .ly document
* Choice depends on whether the LaTeX document is oneside or twoside
* Also, left and right margins have to be determined differently for oneside docs
* Incidentally: Improve indentation of \paper block in generated .ly code
Resulting LilyPond code
* for a onesided document:
```lilypond
\paper{
#(set-paper-size "lyluatexfmt")
print-page-number = ##f
print-first-page-number = ##t
first-page-number = 1
top-margin = 68.327744\pt
bottom-margin = 56.905502\pt
left-margin = 71.131882\pt
two-sided = ##f
line-width = 369.88591003418\pt
#(define fonts
(make-pango-font-tree "Linux Libertine O"
"Linux Biolinum O"
"InconsolataN"
(/ staff-height pt 20)))
}
```
* for a twosided document:
```lilypond
\paper{
#(set-paper-size …
```
> Fix horizontal alignment with insert=fullpage

- examples/wrappingcommands.tex
- lyluatex.lua
- lyluatex.md
- lyluatex.sty
- lyluatexbase.cls
This PR includes several tools for customization:
- `\lynewenvironment` lets one define wrappers for `ly` without most of the drawbacks mentionned in the doc (especially the `[]` for empty optional arguments);
- as `\lynewenvironment` doesn't allow adding lilypond code between `\begin{ly}` and `\end{ly}` (but only latex code before and after), four new parameters allow it in various places, which must be defined to a filename (or a list of filenames) to include (without '.ly'):
- `include_header`;
- `include_footer`;
- `include_before_body`;
- `include_after_body`;
- `\lysavefrag{FILE}` allows defining lilypond code to be saved to `tmp-ly/FILE.ly`, so that it may be called from `include_...`.
> Customization commands

- lyluatex.lua
- lyluatex.md
- lyluatex.sty
If given the `\paper { system-count }` option is set in the ly_code. This can be very useful when LilyPond would by itself break the music on too many systems (e.g. one full system plus one measure), where forcing the system-count can make it work.
Produces
```lilypond
\paper{
system-count = 2
two-sided = ##f
```
in the relevant portion of the generated ly file
> Add system-count option 

- lyluatex.lua
- lyluatex.md
I think the 'showfailed' option should not only cover cases when LilyPond
fails to produce a score but also when it can't be started.
With the showfailed option a failure to start LilyPond does not result
in an err() but in a warn() with the same text, and a box is written
into the document like the one reporting a failed score compilation.
With this option it is for example possible to have people successfully
compile a document without a proper LilyPond installation (useful when
they only care for the content or for technical assistance).
MWE:
```tex
\documentclass{article}
\usepackage{lyluatex}
\begin{document}
\lilypond[program=Foo,showfailed]{ c' }
\end{document}
```
> Gracefully handle failed LilyPond start with 'showfailed' option

- lyluatex-lib.lua
- lyluatex.lua
This is an initial commit at factoring out commonly usable functionality to a separate module. For now I have moved all the local functions to a new file `lyluatex-lib.lua` that are unrelated to `lyluatex`'s actual work.
I think there can be more code to be moved and reused from other packages/modules. One thing, though: I have the impression that the code factored out is the code that is totally unrelated to LilyPond scores but rather concerned with managing a Lua-based LaTeX package. If that's correct (I'm not too sure about my perception of these things) it might be something to consider to factor this out to a completely independent module/package that can be used from arbitrary packages (I think I would love to use the option handling functionality from arbitrary packages without …
> Factoring out local functions to lyluatex-lib module

- lyluatex-lib.lua
- lyluatex-options.lua
- lyluatex.lua
- lyluatex.sty
I think it is a good idea to factor out an additional module `lyluatex-options`.
With that separation third-party code (including my own, I'm talking of a public package like [lyluatexmp](https://github.com/uliska/lyluatexmp) and private packages for custom project code) can either include either the option handling infrastructure or only the generic toolkit.
Probably it would also be a good idea to move those two Lua modules `lyluatex-lib` and `lyluatex-options` to a new separate LuaLaTeX package so it could be distributed and used independently from `lyluatex` altogether. But I'm not so sure how that would have to be done and how a pure-Lua package would actually be integrated in something like TeXLive (maybe it would simply be installed and not be used with `\usepackage` at all).
What …
> lyluatex-options

- lyluatex-options.lua
Small addition. Presumably irrelevant for use in `lyluatex` itself.
This may be used to use the function only for parsing the key/value argument
without the context of option declarations.
> Allow check_local_options to skip sanitization step

- lyluatex-options.lua
A helper function to create a table with current options superseded
by local options. This is not needed in lyluatex where the same result
is achieved through the Score object, but typically a client is required
to perform this merge for *any* score (or other element).
@jperon there may be a few more minor PRs coming, although I really have to get back to writing *content*. But I want to drive my [lyluatexmp](https://github.com/uliska/lyluatexmp) package to the initial point where I can replace the old solution with the new package (i.e. have one command `\lyfilemusicexample` ready to be used). In that process I find that a number of tool functions “appear“ that need to be factored out, some to my own helper modules but some also to `lyluatex`. Maybe it is a good idea to merge these …
> optlib.merge_options

- lyluatex-options.lua
Nested curly braces in an optional argument break the existing code, if
a closing brace happens to be followed by a comma, like in
```tex
caption={Score with \emph{two}, three or four bars}
```
This commit keeps track of the nesting level to ensure the whole argument
is stored as a single option value.
(Faulty input will result in follow-up errors, but these should be clear
from the LaTeX error messages).
> Let check_local_options handle nested curly braces

- lyluatex-lib.lua
- lyluatex.lua
- lyluatex.sty
Fix #204: MiKTeX behavior isn't the same as TexLive's with io.popen. I
don't know why, but on MiKTeX, we have to add a level of quotes, and
it doesn't seem to be able to write code to stdin.
Incidentally, when LilyPond fails on a score, compilation is re-tried
with debug=true.
> Retry lilypond command when failed

- lyluatex.md
- lyluatexmanual.cls
I don't have the time to fully review the manual, which by now contains lots of text. What I *did* is review the introductory texts, hopefully giving a smoother introduction to people and giving those a better chance of understanding why it should be of interest who don't know yet what to make of that package.
With regard to the remaining text I think we can assume everything is OK. What *might* be a good idea, though, is going through the list of options in `lyluatex.sty` and make sure each of them is covered in the manual.
> Manual: Review introductory texts

- lyluatex.sty
These are now required in lyluatextools, so the RequirePackage is
not needed anymore in lyluatex.sty
> Remove RequirePackage-s

- lyluatex.sty
- lyluatextools.sty
The xkeyval functionality is already needed in lyluatextools,
i.e. when this is loaded independently or before lyluatex.
(My use case is that I load lyluatextools, then set up my option handling
and configuration and then already use these options when loading
lyluatex and lyluatexmp).
> Move xkeyval dependency to lyluatextools

- lyluatex-options.lua
This is syntactic sugar for accessing option values from the TeX side.
> Add Opts:use_option(key) method

- lyluatex-options.lua
I've come to the conclusion that it's a courtesy to the user to
reduce the need to use \directlua wherever possible ...
Use case: In a document preamble it is with this patch possible to write
```tex
\RequirePackage[%
left=\lyuseoption{my_opts}{layout_left},%
right=\lyuseoption{my_opts}{layout_right},%
]{geometry}
rather than having to call `my_opts:use_option(layout_left)` in a `\directlua` clause
```
> \lyuseoption as wrapper to Opts:use_option

- lyluatex.lua
These changes made it work for me on windows 11 with miktex, running lualatex from the console or texniccenter.
It's more a workaround than a proper solution but maybe it helps you finding the issue with miktex or someone else in the meantime.
> support MiKTeX with LilyPond ≤ 2.22
