README.en.md

I noticed that the README had been updated and so updated the translation.

Updated translation of README

---

lyluatex.lua
lyluatex.sty

Hi,
As a means of understanding what's happening I have translated the `.sty` and the `.lua` files to English. I admit that along the way I made other changes too, I hope they are not controversial in any way.
I have collected a number of questions and direct ideas (i.e. ideas for immediate enhancements, without thinking about a longer-term strategy to extend the package with substantially new functionality. I'll add them as issues.

Translate to English

---

lyluatex.sty

Admittedly a little bit of vanity ...

Add \lyluatex command for typesetting the package name

---

lyluatex.lua
lyluatex.sty

Here you are; I did it so that options with their default values are set on one statement.

Option handling

---

lyluatex.lua
lyluatex.sty

This PR is based on #41, which should be reviewed and merged first.
It should fix #21 and #33.

Includepaths

---

Makefile
lyluatex.lua
lyluatex.md
lyluatex.sty
lyluatexmanual.cls
test-alignment.tex

If `cleantmp=true` is given as a package option, the temporary files (within `tmp_ly`)
that aren't listed in `jobname.list` will be deleted.

`cleantmp` option

---

examples/relative.tex
lyluatex.lua
lyluatex.sty
test.tex

`relative`

---

lyluatex.lua
lyluatex.sty
test.tex

- better way to capture the `ly` body;
- #91.
I didn't implement `\intertext`. @uliska, I think we should merge this as is for now, but leave #91 open to discuss and implement `\intertext` (IMHO, the name isn't good for that option).

Process input buffer

---

lyluatex.lua
lyluatex.sty
test.tex

Following @rpspringuel's suggestion about #104.

Let the user define his own `verbatim` environment

---

examples/verbatim.tex
ly/Sphinx/Sphinx.ly
lyluatex.lua

Check for % begin verbatim parts in code to be printed verbatim.
Hm, this will probably conflict (merge-wise, not content-wise) with #107

Implement % begin verbatim

---

lyluatex.lua
lyluatex.sty

printfilename

---

lyluatex.lua
lyluatex.sty

As per lilypond-book requirement

Add 'intertext' option and \lyIntertext to make appearance configurable

---

lyluatex.lua
lyluatex.sty

Fix #125
Incidentally, refactor functions that return lilypond code.

papersize option

---

lyluatex.lua
lyluatex.sty

See https://github.com/jperon/lyluatex/issues/45#issuecomment-364759189
Plus a fix for ensuring system-by-system scores start on a new paragraph.

Auto inline

---

lyluatex.md

Is this the version we are currently aiming at?

Add version as subtitle to manual

---

examples/print-only.tex
lyluatex.lua
lyluatex.sty

do-not-print option

---

lyluatex.md

As per
https://github.com/jperon/lyluatex/issues/47#issuecomment-476510105,
thanks to @fedelibre.

Document out-of-tree build

---

lyluatex.lua

Fix #238: problem when including empty scores.

---

lyluatex.md

Document insert=system oddities

---

lyluatex.sty
lyluatextools.sty

All options in one auxiliary package.
Closes #251.

lyluatextools

---

lyluatex.lua

Option -dgs-never-embed-fonts when available

---

lyluatex.lua

Fix count_systems

---

lyluatex.lua

Fix compatibility with polyglossia

---

lyluatex.lua

Fix includepaths

---

lyluatex.lua
lyluatex.md
lyluatex.sty
lyluatexbase.cls
lyluatexmanual.cls
new_release.lua

Fix fonts handling for LilyPond >= 2.25.4
